# Generated by Django 4.1.1 on 2022-10-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=128)),
                ('product_num', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('pln', 'PLN'), ('eur', 'EUR')], default='PLN', max_length=10)),
            ],
        ),
    ]
