# Generated by Django 4.1.1 on 2022-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_associate_alter_orders_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('tak', 'TAK'), ('nie', 'NIE')], default='NIE', max_length=3),
        ),
    ]
