# Generated by Django 4.1.1 on 2022-10-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_worker_name_orders_associate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associate',
            new_name='Associates',
        ),
    ]
