# Generated by Django 4.1.1 on 2022-10-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_associate_associates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associates',
            new_name='Associate',
        ),
    ]
